rosys/__init__.py
tests/conftest.py
tests/test_event.py
tests/test_path_planning.py
tests/test_robot.py
tests/test_time.py

By not auto-using all fixtures we can greatly reduce test execution time.

Speedup Test-Execution

---

.gitignore
examples/path_planning_analysis/main.py
rosys/pathplanning/delaunay_planner.py

In some scenarios the path planning takes pretty long, e.g. 5 seconds on a MacBook. Most time is spent with searching paths in the triangular graph. Since we consider multiple ways from the starting pose into the triangular mesh and multiple ways out to the final pose, the number of combinations can get very large, e.g. 13x7=91 in our specific example. Even if every individual search takes only 0.05s, it adds up quickly to multiple seconds.
This PR limits the number of terminal path segments by choosing the 3 shortes splines each. This reduces the number of combinations from 91 down to 9, resulting in a 10x speedup.
In most cases the terminal path segments are anyway combined with consecutive splines to form a longer spline with less turns and interruptions. So the limited choice of …

Improve path planning performance

---

README.md
docs/generate_reference.py
docs/src/example_cameras_remote.py
docs/src/example_simulation_speed.py
mkdocs.yml

This PR follows up on discussion #45 and propagates the consequent use of RoSys' own lifecycle registration functions.
I had to update the mkdocs config a little bit. We'll have to see if the doc generation and deployment still works.

Use `rosys.on_startup()` instead of `app.on_startup()`

---

rosys/run.py
rosys/vision/rtsp_camera_provider_hardware.py
scripts/watch_wifi_configs.py

This PR applies some additional checks to ensure we do not create zombie processes. In one of our projects we saw many of these:
```
message+  725270  0.0  0.0      0     0 ?        Zs   Okt19   0:00 [exim4] <defunct>
message+  725271  0.0  0.0      0     0 ?        Zs   Okt19   0:00 [exim4] <defunct>
root      725282  0.0  0.0      0     0 ?        Zs   Okt19   0:00 [sudo] <defunct>
root      725285  0.0  0.0      0     0 ?        Zs   Okt19   0:00 [sudo] <defunct>
message+  725288  0.0  0.0      0     0 ?        Zs   Okt19   0:00 [exim4] <defunct>
message+  725289  0.0  0.0      0     0 ?        Zs   Okt19   0:00 [exim4] <defunct>
root      725297  0.0  0.0      0     0 ?        Zs   Okt19   0:00 [sudo] <defunct>
root      725300  0.0  0.0      0     0 ?        Zs   Okt19   0:00 [sudo] …
```

Ensure no zombie processes are left over by run.sh

---

rosys/driving/odometer.py

I noticed that there are quite some things to be aware of if you want to reset the odometer to the initial position. This PR provides a handy reset method to take care of the details.

Introduce odometer.reset

---

rosys/driving/__init__.py
rosys/driving/driver.py
tests/test_automations.py

This PR introduces a flag `driver.abort_driving` which interrupts the current driving loop. This can be used if the current driving path becomes invalid. For example due to a suddenly appearing obstacle or large position shifts.

Provide method to abort current driving loop

---

rosys/automation/automation_controls_.py

The resume button of automation controls is now disabled if the automation is disabled (for example due to a bumper detecting an obstacle).
Also some other code simplifications due to new NiceGUI features.

Disable resume button if automator is disabled

---

rosys/analysis/videos_page_.py

This PR uses the existing media file url from the `ui.video` element for `ui.download` because the media url allows chunked download and caching through NiceGUI On Air.

Videos Page: Use existing media url for download

---

rosys/vision/usb_camera/usb_camera_scanner.py

add ID_PATH and DEVNAME as fallbacks for the camera id

---

rosys/vision/calibration.py
rosys/vision/camera_objects_.py
rosys/vision/camera_projector.py
rosys/vision/detector_simulation.py
tests/test_camera_calibration.py

This PR solves issue #72 by adding the behind-the-camera check from `project_from_image` to `project_to_image`.

Consistently handle points behind the camera when projecting from and to an image

---

rosys/hardware/bms.py

This PR adds a `base_consumption` attribute to the `BmsHardware` class with a default value of -0.4. This enhancement refines the charging state determination by comparing the current consumption against the `base_consumption`, thereby improving the accuracy of monitoring the `is_charging` state.

Add base consumption attribute to BmsHardware

---

rosys/hardware/estop.py

`active = any(int(words.pop(0)) == 0 for _ in self.pins)`
if words lookes like this [0,1] this only pops the 0 and the rest is not popped. Words will look like this [1] but should be [].
This pops all estop vales first and than uses any.

fixed estop corehandling

---

rosys/driving/keyboard_control_.py

Parameterize the connection checking behavior of the keyboard control:
* add `connection_timeout` to specify the amount of time the health response is allowed to take
* add `check_connection_interval` to specify the interval the keyboard control performs this a connection test
* defaults are set to 1.0s (0.5s has proven to be too short in practice)
* add event `CONNECTION_INTERRUPTED` that is emitted when a connection test encounters a TimeoutError

Keyboard control timeouts

---

rosys/vision/image_route.py

when recreating a camera route the old route is removed first to not have duplicate routes.

readding cameras first removes old route

---

rosys/hardware/robot_brain.py

This PR refactors the `enable_esp` method to utilize the updated `./flash.py` script, leveraging the new `enable` flag introduced in Lizard version 0.1.8. This change streamlines the process by directly integrating the enable functionality within the flash.py execution.

Esp activation

---

rosys/vision/mjpeg_camera/mjpeg_camera.py
rosys/vision/mjpeg_camera/mjpeg_camera_provider.py
rosys/vision/mjpeg_camera/mjpeg_device.py
rosys/vision/mjpeg_camera/vendors.py

Adds support for multiple cameras connected through a single ip.
In particular, ids now have an index after the mac.
For axis devices (the only ones supported right now), we ask for the the video status at 'axis-cgi/videostatus.cgi' during camera discovery and create cameras based on that rather then a single one.
The option to supply an ip to Camera.connect is also added to avoid triggering a slow arp-scan for the same ip multiple times.

Mjpeg multiple cameras

---

rosys/vision/rtsp_camera/arp_scan.py
rosys/vision/rtsp_camera/rtsp_camera.py
rosys/vision/rtsp_camera/rtsp_camera_provider.py
rosys/vision/rtsp_camera/rtsp_device.py

This pull request adds and uses an optional ip parameter to the RtspCamera.
It mirrors the same functionality in the MjpegCamera and respective Provider.
Essentially, this uses the ip from the scan that is done anyway which saves one arp-scan per camera that is connected.

Rtsp camera ip connect

---

rosys/persistence/registry.py

If somehow the content of a backup is not serializable the error message was quite cryptic:
```
rosys_1       | 2024-05-02 07:21:44.142 [ERROR] nicegui/app/app.py:118: Object of type Decimal is not JSON serializable
rosys_1       | Traceback (most recent call last):
rosys_1       |   File "/home/zauberzeug/.local/lib/python3.11/site-packages/nicegui/background_tasks.py", line 52, in _handle_task_result
rosys_1       |     task.result()
rosys_1       |   File "/home/zauberzeug/.local/lib/python3.11/site-packages/nicegui/client.py", line 290, in result_with_client
rosys_1       |     await result
rosys_1       |   File "/home/zauberzeug/.local/lib/python3.11/site-packages/rosys/rosys.py", line 225, in shutdown
rosys_1       |     await persistence.backup(force=True)
rosys_1       |   File …
```

Log problematic content if backup fails

---

rosys/vision/mjpeg_camera/mjpeg_camera_provider.py
rosys/vision/mjpeg_camera/mjpeg_device.py
rosys/vision/mjpeg_camera/vendors.py
rosys/vision/rtsp_camera/arp_scan.py
rosys/vision/rtsp_camera/rtsp_camera_provider.py
rosys/vision/rtsp_camera/vendors.py

This PR adds support for mjpeg-based [Motec ip cameras](https://www.motec-cameras.com/)
The changes are:
- add Motec as a mjpeg vendor
- change VendorType to ~~IntEnum~~ Enum for both mjpeg and rtsp
- remove check that disconnects cameras which are not in the arp-scan but are still connected
- clean up find_cameras return values
- refactor mjpeg_device.py
~~IntEnum can be changed to Enum, but may lead to errors in other projects~~

Add Motec as a mjpeg-vendor and refactor camera providers

---

rosys/vision/usb_camera/usb_camera.py

This PR fixes a ugly error which can happen on shutdown.

Handle None value from io_bound capture.read in usb_camera.py

---

rosys/automation/automator.py
rosys/event.py
rosys/testing/fixtures.py

This pull request ensures that non-async functions are called immediately. The usage of `invoke` was wrong because it's an async function itself and hence will always be awaitable.

Emitting events should call non-async functions synchronously

---

rosys/analysis/asyncio_warnings.py

This pull request improves the `asyncio_warnings.ui()`.

Make asyncio warnings ui container accessible and hide controls

---

rosys/vision/mjpeg_camera/mjpeg_camera.py
rosys/vision/mjpeg_camera/mjpeg_camera_provider.py
rosys/vision/rtsp_camera/rtsp_camera.py
rosys/vision/rtsp_camera/rtsp_camera_provider.py

Two changes that I felt were hard to find a good name for:
- ip is now stored in both Rtsp and Mjpeg Network cameras such that they can quickly reconnect on startup and are less dependent on network scans
- username and passwords are not overwritten by the `MJpegCameraProvider` when loading cameras from persistence
An app should now be able to set up and configure cameras and have everything be loaded and setup as-is on the next start.

More static cameras

---

rosys/geometry/point3d.py

This PR adds two helpful builder functions to the `Point3d` class.

Create Point3d from tuple and list.

---

rosys/vision/detector_simulation.py

This pull request allows to change the simulated delay of a detection.

Make simulation delay in detector configurable

---

rosys/vision/camera/camera.py

- set streaming to True by default
- use a should_stream field for persistence (currently if the stream task ends or is not yet started, steaming=False could be written into persistence)
- show the "no image" placeholder if the camera is disconnected

Fix camera streaming

---

rosys/vision/camera/calibratable_camera.py

This pull requests adds the `focal_length` parameter to the creator methods of `CalibratableCamera`.

Allow configuration of focal length when building a simulated camera

---

rosys/vision/multi_camera_provider.py

`CameraProvider` derives from `rosys.persistent_module`, so each provider will have a `request_backup` function.
Here we overwrite that functions, since we really want all cameras to be backed up by their respective providers.
Alternatively, we could iterate over `cameras` and back them up into `rosys.vision.multi_camera_provider.MultiCameraProvider.json`. 
I think this is less fitting though since the MultiCameraProvider is meant to be a proxy rather than a provider by itself.

Add request_backup to MultiCameraProvider

---

docs/src/example_camera_control.py
rosys/geometry/point3d.py
rosys/vision/mjpeg_camera/axis_mjpeg_device.py
rosys/vision/mjpeg_camera/mjpeg_camera.py
rosys/vision/mjpeg_camera/mjpeg_camera_provider.py
rosys/vision/mjpeg_camera/mjpeg_device.py
rosys/vision/mjpeg_camera/mjpeg_device_factory.py
rosys/vision/mjpeg_camera/motec_mjpeg_device.py
rosys/vision/mjpeg_camera/vendors.py

The goal here is primarily to add the ability to change the settings on axis camera devices.
This works differently from all previous interfaces since it does not change anything on the camera device itself, but rather just edits the url that is used to request images.
As a result that functionality really needs to be implemented inside the MjpegDevice and I have thus separated devices with different interfaces into subclasses of MjpegDevice.
Some logging was also added to the providers `scan_for_cameras` method.
Considerations I have for the future of this:
- The configurable parameters of a camera should really be determined by the device. We now have a discrepancy of parameters between vendors:
Axis devices have a `mirrored` parameter and  Motec devices have options for the …

Axis Settings (MjpegDevice Subclasses)

---

docs/examples/persistence.md
rosys/persistence/__init__.py
rosys/persistence/backup_schedule.py
rosys/persistence/registry.py
rosys/persistence/ui.py
tests/test_persistence.py

This PR adds a backup schedule to backup all files in the persistence folder (`~/.rosys`) once a day as suggested here #108.
The location of the backup, the time it's performed and the number of backup files that are kept is configurable.
Changes:
* move writing of an export file to `persistence.registry`
* add BackupSchedule itself
* add documentation

Add Backup schedule

---

rosys/testing/fixtures.py

This pull request moves the log setup into the integration test fixture to prevent it from loading when pytest loads all fixtures.  Before the log formatting was applied to all pytests as long as rosys is installed via pip.

Prevent log config from loading for other pytest projects

---

rosys/vision/camera_provider.py
rosys/vision/multi_camera_provider.py

This adds the `scan_for_cameras` method to the `MultiCameraProvider` which in turn calls it on all its providers.
For this, all `CameraProvider`s need to support the `scan_for_cameras` method which is now an abstract method of the parent class.
Adding the method as an `abstractmethod` may require action on all derived `CameraProviders` outside of rosys.
Another option would be to add it as a default that does nothing.
The central question here would be if all providers can scan for new cameras somehow or if some need a fixed list provided by the application code.

MultiCameraProvider camera scanning

---

rosys/analysis/tracking.py
rosys/automation/automator.py

This PR replaces the `stack` list with a dictionary, mapping a unique ID to function names. After running the function, we don't _pop_ the last function name, but delete the item with the respective ID from the dictionary. Since Python dictionaries preserve their item's order, we can simply display the current state by joining all dictionary values.
Has been successfully tested with the code snippet from https://github.com/zauberzeug/rosys/issues/147#issue-2408992831.

Fix @track decorator when used with parallelize()

---

rosys/vision/detector_hardware.py

The detector disconnects/reconnects and does not provide proper detections if the image is too big. This is caused by the default message size of 1 MB in the Detector container. This PR increases the default for RoSys to 10 MB.

Allow images up to 10 mb for the detector

---

rosys/automation/parallelize.py
tests/test_automations.py

We noticed that `rosys.automation.parallelize()` called both coroutines by turns, independent if one of them is sleeping longer than the other, slowing down the faster one. Here is an example:
```py
import rosys
async def slow():
for i in range(10):
print(f'slow {i}')
await rosys.sleep(0.5)
async def fast():
for i in range(50):
print(f'fast {i}')
await rosys.sleep(0.1)
async def parallel():
await rosys.automation.parallelize(slow(), fast(), return_when_first_completed=True)
automator = rosys.automation.Automator(None)
ui.button('Run', on_click=lambda: automator.start(parallel()))
ui.run()
```
This PR fixes this issue with the help of Claude AI by keeping track of waiting and completed futures.
It also adds a pytest. But even though it tests the general behavior of …

Allow parallelizing coroutines with different sleep intervals

---

rosys/testing/fixtures.py
tests/test_cameras.py
tests/test_event.py
tests/test_mjpeg_camera.py
tests/test_time.py

Since we provide an entry point for the RoSys pytest plugin, we decided to use a more discriminative name.

Rename integration fixture to "rosys_integration"

---

rosys/vision/camera/configurable_camera.py
rosys/vision/mjpeg_camera/mjpeg_camera.py
rosys/vision/rtsp_camera/rtsp_camera.py
rosys/vision/simulated_camera/simulated_camera.py

Currently, when setting parameters the camera checks if it is connected and simply drops the values if it is not (with the idea that if we cannot set the values on the camera then we cannot do anything).
This PR now saves the values to cache if the camera is disconnected so that upon a reconnect, the values will be applied.

Allow setting parameters on disconnected cameras

---

rosys/geometry/pose.py

I wanted to know how much the robot has to turn to face a target.
You first have to get the direction to the target and then calculate the difference between the direction and your robot's current yaw.
This PR combines this approach in the `Pose.relative_direction(Point | Pose)` function to make it more easily available.
@falkoschindler the angle parameter of `rotate(self, angle: float)` collides with `rosys.helpers.angle`. I imported it as `helpers_angle` for now, but I don't really like it.

Add relative_direction function to Pose

---

rosys/vision/camera_objects_.py

Caused by #153, resolving the frame on a different process fails:
```
Traceback (most recent call last):
File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 261, in _process_worker
r = call_item.fn(*call_item.args, **call_item.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/rodja/Projects/rosys/rosys/vision/camera_objects_.py", line 81, in get_rotation
return calibration.extrinsics.resolve().rotation.R  # computing euler rotation is cpu expensive
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/rodja/Projects/rosys/rosys/geometry/object3d.py", line 42, in resolve
return self.relative_to(None)
^^^^^^^^^^^^^^^^^^^^^^
File "/Users/rodja/Projects/rosys/rosys/geometry/object3d.py", …
```

Remove run.cpu_bound for rotation computation

---

docs/src/example_coordinate_frames.py
rosys/vision/__init__.py
rosys/vision/simulated_camera/__init__.py
rosys/vision/simulated_camera/simulated_calibratable_camera.py

To avoid rewriting the very simple implementation of a `SimulatedCalibratableCamera` in every project, this PR adds it to `rosys.vision`.
~~NOTE: due to circular dependencies, the implementation was placed in the `__init__.py`.~~

Add `SimulatedCalibratableCamera`

---

examples/hello_bot/main.py
rosys/driving/driver.py
tests/test_automations.py

Our robot needs to drive continuously between two GNSS coordinates while adjusting its heading. For each segment we use `drive_spline`, but it stops after completing the spline drive.
This PR adds a parameter for not stopping at the end `stop_at_end` and does some refactoring in the `Driver` class

Do not stop after driving a spline

---

rosys/vision/camera_provider.py

This PR provides a convenience property to get the first connected camera of a `CameraProvider`

Provide property to get first connected camera

---

rosys/analysis/timelapse_recorder.py

Before this PR, the camera name was shown. Now this can be configured with a lambda function to show more specific informations.

Allow specifying the info string drawn on every frame of a timelapse video

---

rosys/run.py

This PR tries to solve issues #43 and #162 by using NiceGUI's run functions instead of own implementations.
@rodja I removed `process_pool` and `thread_pool`. Do you think this is ok? Or do we need to use our own pools for some reason?

Use NiceGUI's run.io_bound and run.cpu_bound

---

rosys/driving/odometer.py

This PR fixes a regression introduced by #168. The `ROBOT_MOVED` event used to be only emitted by `handle_velocities`, not by `handle_detection`. Emitting the event too often causes problems in a customer project where we mark camera images as unlinkable every time the robot moves.

Don't emit ROBOT_MOVED in handle_detection

---

rosys/persistence/__init__.py
rosys/persistence/registry.py
rosys/persistence/ui.py

This PR splits the existing functions for exporting and importing the persistence modules to be used in different contexts. The ui buttons and functions remain the same and use the new `get_export` and `restore_from_export` functions now.

More modular functions to use for export and import of persistence modules

---

Dockerfile
docker-compose.yml

This PR uses 3.12-bookworm as the base image since 3.12-buster isn't available. It also installs the optional dev dependencies and RoSys itself.

Fix docker image

---

rosys/geometry/pose3d.py

This PR adds a `point_3d` property to `pose3d`, based on `point` and `point_3d` from `pose`.

Add point_3d property to pose3d

---

rosys/vision/rtsp_camera/jovision_rtsp_interface.py
rosys/vision/rtsp_camera/rtsp_camera.py
rosys/vision/rtsp_camera/rtsp_device.py

Adds the bitrate as a parameter. The control was already supported through the jovision interface.
Aditionally, I have made some adjustments to the interface:
- username/ password in the header turned out not to be necessary
- some type hints were missing
- there was an extra channelid in the param dict
- the values to be set are easy to set as an incorrect type without noticing so I added a backup `int` cast

add bitrate parameter to RTSP cameras

---

rosys/geometry/rotation.py
rosys/vision/calibration.py

While creating a calibration, I found that the zero-function of rosys.geometry.Rotation uses integers, which causes `cv2.Rodrigues` to fail, because it expects floats.
While using `.astype(np.float32)` helps, using floats directly makes it easier to use in the future.
```python
import cv2
import numpy as np
from rosys.geometry import Pose3d, Rotation
extrinsics = Pose3d(x=0, y=0, z=0, rotation=Rotation(R=[[0, 0, 0], [0, 1, 0], [0, 0, 1]]))
R = extrinsics.rotation.matrix.astype(np.float32)
Rod = cv2.Rodrigues(R.T)[0]
extrinsics = Pose3d(x=0.0, y=0.0, z=0.0, rotation=Rotation(R=[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]))
R = extrinsics.rotation.matrix
Rod = cv2.Rodrigues(R.T)[0]
extrinsics = Pose3d(x=0, y=0, z=0, rotation=Rotation(R=[[0, 0, 0], [0, 1, 0], [0, 0, 1]]))
R = …
```

Fix calibration.project_to_image

---

rosys/analysis/timelapse_recorder.py

As requested in https://github.com/zauberzeug/field_friend/pull/155#issuecomment-2315503366, this PR adds logging to the video compression so we can see when it finishes. It also introduces the `ongoing_computations` property which holds a list of all target video filenames which are currently created.

Expose list of ongoing video compressions and improved logging

---

rosys/geometry/point3d.py

Both the dot product and the translation vector in `Point3d.transform_with` are 2D but need to be 1D for `Point3d.from_tuple`, which causes the coordinates to be np.arrays and not floats. https://github.com/zauberzeug/rosys/blob/e3ef8cf8ecfe092789699410cd659ecb471e6a2e/rosys/geometry/point3d.py#L62 
```python
import numpy as np
from rosys.geometry import Point3d, Pose3d, Rotation
point = Point3d(x=0.015, y=0.135, z=0.357)
pose = Pose3d(x=0.2965439264325891, y=-0.004233199581623145, z=0.3609662018089546,
rotation=Rotation.from_euler(-138.1, -1.3, 89.9))
new_point = Point3d.from_tuple((np.dot(pose.rotation.R, point.array) + pose.translation_vector).flatten())
print(new_point)
new_point = Point3d.from_tuple((np.dot(pose.rotation.R, point.array) + pose.translation_vector))
print(new_point) …
```

Fix Point3d.transform_with

---

rosys/vision/rtsp_camera/jovision_rtsp_interface.py

For some reason creating the client in the init doesn't work. We revert to creating it in the function

fix broken async client usage

---

rosys/vision/mjpeg_camera/axis_mjpeg_device.py

Previously, the set parameter value was not remembered, so it could not be reset (since the system thought the value was still the original)
This PR properly remembers the parameters that were set.

Axis Parameter Fixes

---

rosys/vision/camera_provider.py
rosys/vision/multi_camera_provider.py

This PR fixes the removal of cameras in the `multi_camera_provider`. 
The problem was that the camera removal works by modifying the dict returned by `self.cameras`. However, the `multi_camera_provider` overwrites this method to return a joined dict of all sub-providers. Consequently, the deletion had no effect. 
This PR also adds a deprecation warning for the `prune_images` function which is outdated because images is a dequeue now.

Fix camera removal

---

rosys/hardware/robot.py
rosys/hardware/wheels.py

Upon investigating positioning errors of our [gnss simulation](https://github.com/zauberzeug/field_friend/blob/main/field_friend/localization/gnss_simulation.py), that is based on the wheels pose, I noticed that the timing in `wheels.step` is off by a little. The error per step is not high, but it adds up quite fast.
```python
import numpy as np
from rosys import simulation_ui
from rosys.automation import Automator, automation_controls
from rosys.driving import Driver, Odometer, Steerer, keyboard_control, robot_object
from rosys.geometry import Pose, Prism, Spline
from rosys.hardware import RobotSimulation, WheelsSimulation
shape = Prism.default_robot_shape()
wheels = WheelsSimulation()
robot = RobotSimulation([wheels])
odometer = Odometer(wheels)
driver = …
```

Fix wheels timing error

---

rosys/event.py

On multiple occasions we needed to wait for the next call of an event. Instead of waiting in a loop or setting some internal variable this PR allows waiting for an event directly.
```python
import rosys
from rosys.event import Event
event = Event()
event.register(lambda *args: print('Event fired!', *args))
async def wait_for_event_timeout(timeout: float | None = 10.0):
print('Waiting for event with timeout', timeout)
value = await event.emitted(timeout)
print('Event received!', value, type(value))
async def wait_for_event():
print('Waiting for event')
value = await event
print('Event received!', value, type(value))
ui.button('Wait for event with timeout', on_click=wait_for_event_timeout)
ui.button('Wait for event', on_click=wait_for_event)
ui.button('Emit', …
```

Awaitable events

---

poetry.lock
pyproject.toml
rosys/analysis/timelapse_recorder.py
rosys/automation/automator.py
rosys/vision/image.py
tests/test_automations.py

- Adds `svg_overlays` property to image to allow storing additional augmentations.
- Render `image.svg_overlays` content with newly introduced dependency `cairosvg` to each timelapse image
- Fix issue with not existing `videos` path

Allow svg overlays for timelapse videos

---

docs/src/example_camera_control.py
rosys/vision/camera/camera.py
rosys/vision/mjpeg_camera/axis_mjpeg_device.py
rosys/vision/mjpeg_camera/mjpeg_camera.py
rosys/vision/mjpeg_camera/mjpeg_device.py
rosys/vision/mjpeg_camera/mjpeg_device_factory.py
rosys/vision/mjpeg_camera/motec_mjpeg_device.py
rosys/vision/rtsp_camera/rtsp_camera.py
rosys/vision/rtsp_camera/rtsp_device.py
rosys/vision/simulated_camera/simulated_camera.py
rosys/vision/simulated_camera/simulated_device.py
rosys/vision/usb_camera/usb_camera.py
rosys/vision/usb_camera/usb_device.py
tests/test_cameras.py
tests/test_mjpeg_camera.py

This PR sends camera images directly from the `Device` to the `Camera` without the camera having to poll on its own.
That causes a much more stable frame-rate and more accurate image timing.
It also improves the processing the `RtspDevice`s Pipe stream. On loop iteration we now read as much data as possible from the pipe and only process the last image. This enables the system to catch up to the real camera stream much faster.

Camera image callbacks

---

rosys/vision/simulated_camera/simulated_device.py

We had issues with failing tests, because the camera simulation was too slow since https://github.com/zauberzeug/rosys/pull/197.
This PR brings back a check whether the image is created in a test or not, that was removed in https://github.com/zauberzeug/rosys/pull/197/commits/d9e612ad684a23213ca73ae49aac3f69f5e4f145#

Fix slow SimulatedCamera tests

---

rosys/hardware/battery_control.py
rosys/hardware/bumper.py

We still notice issues with https://github.com/zauberzeug/lizard/issues/66 (`Unknown Property "level"` and `Unknown Property "active"`) until then setting them to 0 and false on p0 helps.

Temporary fix for Lizard issue 66

---

rosys/persistence/__init__.py
rosys/persistence/registry.py
rosys/rosys.py

We noticed that persistent modules are not backed up during RoSys shutdown or restart. This problem can be reproduced with this simple example:
```py
from rosys import persistence
class Model(persistence.PersistentModule):
def __init__(self) -> None:
super().__init__()
self.checked = False
def restore(self, data: dict) -> None:
self.checked = data.get('checked', False)
def backup(self) -> dict:
print('Backup called')
return {'checked': self.checked}
model = Model()
ui.checkbox('Checked').bind_value(model, 'checked')
ui.run()
```
When causing a reload by touching the Python file, the print statement doesn't appear. The reason is that `backup()`, which is called during shutdown, is decorated with `@awaitable`, wrapping it with an `io_bound` call. But `io_bound` is …

Fix backup during shutdown

---

rosys/vision/image_route.py

adds a `max_size` parameter to determine the necessary shrink based on the image size
resulting shrink is always the maximum between (`shrink`, `shrink_from_max_size`)
meaning you can still apply a base shrink AND set a maximum
Here, "size"  (in `max_size`) refers to the maximum dimension of the image. I would like some feedback on that name. 
I was also considering a maximum pixel area instead (e.g. 1.5 MP), but felt like that would be more confusing.

image route max_size parameter

---

rosys/vision/mjpeg_camera/axis_mjpeg_device.py
rosys/vision/mjpeg_camera/mjpeg_camera.py
rosys/vision/mjpeg_camera/mjpeg_device.py
rosys/vision/mjpeg_camera/mjpeg_device_factory.py
rosys/vision/mjpeg_camera/motec_mjpeg_device.py
rosys/vision/rtsp_camera/rtsp_camera.py
rosys/vision/rtsp_camera/rtsp_device.py
rosys/vision/simulated_camera/simulated_camera.py
rosys/vision/simulated_camera/simulated_device.py
rosys/vision/usb_camera/usb_camera.py
rosys/vision/usb_camera/usb_device.py

Gets the timestamp for images in each camera earlier (mainly before any further image procession).
This is not critical but should make the timestamps a little more accurate.

Earlier image timestamping

---

rosys/geometry/line_segment.py

When intersecting two parallel line segments, e.g. `(0, 0)--(1, 0)` and `(0, 1)--(1, 1)`, the determinant `d` becomes zero and the division is undefined. We should return `None` in this case.

Fix intersection of parallel line segments

---

rosys/analysis/legacy/asyncio_page.py
rosys/hardware/lizard_firmware.py
rosys/run.py
rosys/vision/mjpeg_camera/mjpeg_camera.py
rosys/vision/simulated_camera/simulated_device.py
rosys/vision/usb_camera/usb_camera.py
rosys/vision/usb_camera/usb_device.py

As noticed by @denniswittich, IO- and CPU-bound functions in RoSys are missing type annotations for parameters and return values. Apart from that `run.cpu_bound` is missing `kwargs`.
While this PR adds both, it unveils several type errors in connection with `run.cpu_bound` and `run.io_bound`:
```
rosys/run.py:26: error: Missing return statement  [return]
rosys/run.py:28: error: Return value expected  [return-value]
rosys/run.py:46: error: Missing return statement  [return]
rosys/run.py:48: error: Return value expected  [return-value]
rosys/vision/usb_camera/usb_device.py:85: error: Incompatible types in assignment (expression has type "Awaitable[Any] | None", variable has type "tuple[bool, Mat | ndarray[Any, dtype[integer[Any] | floating[Any]]]]")  [assignment] …
```

Add type annotation and kwargs to `run.io_bound` and `run.cpu_bound`

---

rosys/hardware/lizard_firmware.py
rosys/hardware/robot_brain.py

Using `bind_value` on `version_select` leads to a recursion error.
I'm not quite sure yet what causes this, but using `bind_value_to` helps.
Additionally, 329ad6dfb3a1d5507ab1c1ec0af70675d302c7a2 sets the selection to the latest version when the list is updated.
```
rosys_1  | 2024-11-04 23:18:34.374 [ERROR] nicegui/app/app.py:122: maximum recursion depth exceeded
rosys_1  | Traceback (most recent call last):
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/events.py", line 430, in handle_event
rosys_1  |     result = cast(Callable[[EventT], Any], handler)(arguments)
rosys_1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/elements/mixins/value_element.py", line 40, in handle_change …
```

Fix selectable lizard version

---

rosys/vision/camera_provider.py

Adds the option to set the persistence key on `CameraProvider` instantiation to allow for the creation of two or more `CameraProvider`s while still using persistence.
Without setting the key they would overwrite each other.

add persistence_key parameter CameraProvider Constructor

---

.github/workflows/publish.yml

This PR adds multiplatform cache to the publish pipeline. According to [this](https://github.com/docker/buildx/issues/1044) and [this](https://github.com/docker/buildx/discussions/1382) the cache in the registry needs to be separated for different build platforms. So, arm64 and amd64 now each get their own cache location.
To only run the update readme step once, it gets its own job.

update GitHub action to support multiple platforms

---

rosys/hardware/__init__.py
rosys/hardware/esp_pins.py
rosys/hardware/lizard_firmware.py
rosys/hardware/robot_brain.py

In [Lizard's PR #95] (https://github.com/zauberzeug/lizard/pull/95) a check of the pins that could block the flashing was implemented.
This PR added a check and notifications for the UI to warn the user if flashing cannot be performed.

Check Strapping Pins before Flashing P0

---

rosys/geometry/geo.py
rosys/hardware/gnss.py

I noticed a bug when the robot is turning. The angle for the GNSS antenna offset was not calculated correctly

Fix GNSS Antenna Shift

---

rosys/analysis/timelapse_recorder.py

With this PR timelapse recordings work out of the box without the need to create the `~/.rosys/timelapse` dir manually.

Ensure timelapse storage dirs

---

rosys/helpers/deprecation.py
rosys/rosys.py
rosys/vision/rtsp_camera/rtsp_camera.py
rosys/vision/rtsp_camera/rtsp_camera_provider.py
rosys/vision/rtsp_camera/rtsp_device.py
rosys/vision/rtsp_camera/vendors.py

feat: use substream parameter for dahua cameras
DEPRECATION: rename jovision_profile to substream in `RtspCamera` and `RtspCameraProvider`

dahua profile setting

---

rosys/vision/rtsp_camera/rtsp_camera.py

small fix:
`parameters` is a property that only contains values,
we need to use `_parameters` to actually update the `substream` value so it matches `jovision_profile`.
Changes:
- use _parameters instead of parameters

Fix substream parameter setting

---

rosys/hardware/bumper.py

I noticed that `BumperHardware` does not pop correctly from the lizard core output list when the estops are active.
`['1', '1', '1', '3', '0.6960', '-0.7180', '0.0101', '0.0000', '1', '1', '73412']` goes into the `BumperHardware` module and `['3', '0.6960', '-0.7180', '0.0101', '0.0000', '1', '1', '73412']` should come out, but it doesn't.
We never noticed because `StatusControlHardware` pops 2 integers, that electrically behave the same as the bumpers. It occurs now because I added a `ImuHardware` module between them.
```
rosys_1       | 2025-01-21 18:14:42.637 [ERROR] rosys/hardware/bumper.py:55: BumperHardware: ['1', '1', '1', '3', '0.6960', '-0.7180', '0.0101', '0.0000', '1', '1', '73412']
rosys_1       | 2025-01-21 18:14:42.637 [ERROR] rosys/hardware/bumper.py:57: BumperHardware: …
```

Fix Bumper Core Output with EStops activated

---

rosys/vision/rtsp_camera/rtsp_camera.py

the deprecations on this would always be triggered since the functions are automatically called on connect

remove jovision setter and getter deprecation warnings

---

rosys/hardware/gnss.py

The GNSS serial device seems not to be ready right after booting up the computer (https://github.com/zauberzeug/field_friend/issues/264).
With this PR RoSys tries to reconnect every 3 seconds by default.
```
2025-01-23 23:31:27.383 [INFO] rosys/hardware/gnss.py:213: Found GNSS device: /dev/ttyACM1
2025-01-23 23:31:29.253 [INFO] rosys/hardware/gnss.py:218: Connecting to GNSS device "/dev/ttyACM1"...
2025-01-23 23:31:29.256 [ERROR] rosys/hardware/gnss.py:150: Could not connect to GNSS device: /dev/ttyACM1
2025-01-23 23:31:32.257 [INFO] rosys/hardware/gnss.py:218: Connecting to GNSS device "/dev/ttyACM1"...
2025-01-23 23:31:32.259 [INFO] rosys/hardware/gnss.py:153: Connected to GNSS device: /dev/ttyACM1
```
It happens with all of our robots, so releasing this as 0.22.1 would be helpful.

Add reconnecting to GNSS hardware

---

poetry.lock
pyproject.toml

To not restrict which version of NiceGUI a project that's using RoSys needs to install, I set the version to the lowest one that RoSys supports.

Set nicegui version to lowest possible one

---

rosys/analysis/videos_page_.py

This PR updates the `/videos` page displaying the available timelapse videos.
Since streaming those videos from the robot in most cases takes too many resources and requires a very good internet connection, we decided to only provide a download option for the videos.

Improve videos page to only include date picker and video titles but no previews

---

rosys/persistence/converters.py

This PR adds the type of the `cls` argument as the result of the `from_dict` method. A resulting object then has the correct type instead of `Any`.

Add type to from_dict

---

rosys/hardware/imu.py

Currently IMU measurements are ignored if `gyro_calibration < 1`. This PR makes this threshold configurable

Make IMU gyro calibration threshold configurable

---

docs/src/example_camera_control.py

I noticed that the example was not updated, yet.
This PR replaces deprecated `jovision` parameter with new `substream` parameter in the camera control example.

use new `substream` parameter in camera control example

---

rosys/vision/calibration.py
tests/test_camera_calibration.py

- implement redistortion for the pinhole model
- add tests for redistortion
- simplify normalization for fisheye model
- explicitly set unused crop to False for pinhole undistortion

Pinhole Redistortion and minor distortion refactoring

---

Dockerfile

This PR adds required gstreamer packages to the Dockerfile to support RTSP cameras.

Add RTSP camera support to Docker image

---

rosys/hardware/robot.py

This PR allows to add modules to a robot after its initialization. This is needed when you create your own `Robot` class that extends `RobotHardware`, because modules and the robot brain are created on `__init__` and you need the robot brain for additional modules.
I tested it on one of our robots.

Add modules to a robot after initialization

---

rosys/vision/calibration.py
tests/test_camera_calibration.py

feat: add crop_parameter to `undistort_image`
style: make `point_to_rays` private
feat: add overloads to accept `list[Point]` in `distort_image` and `undistort_image`
feat: reshape `image_points` to accept a wider range of input points
feat: reshape points array to `Nx2` before returning it
test: add image undistortion and distortion tests
type: type inputs and outputs as `FloatArray` where applicable
BREAKING CHANGE: `distort_points` and `undistort_points` now return arrays of shape `(N, 2)`

Improved distortion api

---

rosys/automation/app_controls_.py
rosys/automation/automator.py
rosys/automation/schedule.py
rosys/driving/keyboard_control_.py
rosys/driving/odometer.py
rosys/driving/steerer.py
rosys/event.py
rosys/hardware/bumper.py
rosys/hardware/estop.py
rosys/hardware/gnss.py
rosys/hardware/imu.py
rosys/hardware/robot_brain.py
rosys/hardware/wheels.py
rosys/pathplanning/area_manipulation.py
rosys/pathplanning/path_planner.py
rosys/rosys.py
rosys/vision/camera/camera.py
rosys/vision/camera_provider.py
rosys/vision/detector.py
tests/test_event.py
tests/test_odometer.py

I have have had a lot of situations where I was not exactly sure which values an event would produce or these values changed but the consumer was not changed correctly with it.
This PR adds a Generic ParamSpec to the `Event` class which enables users to optinally initialize their events as
```py
my_event = Event[int, str]()
```
or equivalently
```py
my_event: Event[int, str] = Event
```
to let the type checker correctly check the types of the callback in `my_event.register()` and the other functions.

typed Events

---

rosys/vision/detector_hardware.py

Fixes tag upload by properly adding 'tags' to the data dictionary that is sent via socketio.

Fix tag upload in detector hardware

---

examples/camera_arm/main.py
rosys/geometry/__init__.py
rosys/geometry/pose3d.py

I want to share `Frame3dSceneObject` that I built for easier debugging of 3d frames. You only need nicegui's 3d scene and a `Frame3d`, nothing else is needed and they update their positions themselves.
Here I modified the [camera arm example](https://github.com/zauberzeug/rosys/blob/main/examples/camera_arm/main.py)
https://github.com/user-attachments/assets/c5836746-ebcb-4ee9-ad24-41aff7128b4c
I replaced the given page function
https://github.com/zauberzeug/rosys/blob/10c73721be0cd5da5bff8acce540f0e67e94ea9a/examples/camera_arm/main.py#L68-L96
with this:
```python
def page():
keyboard_control(steerer)
with ui.row():
with ui.scene() as scene:
scene.move_camera(y=-2, z=2)
frame_3d_object(anchor_frame)
frame_3d_object(arm1.base, name='Arm 1 Base')
frame_3d_object(arm2.base, name='Arm 2 …
```

Add 3d visualization for Frame3d 

---

rosys/hardware/robot_brain.py

To debug the lizard config generated by RoSys without writing it to the microcontroller, this PR adds a menu item to the ui of the robot brain to download the `.liz` file containing the config.

Add download functionality for lizard configs

---

rosys/vision/camera_provider.py

changes the event parameter type to the already existing generic type so that subtypes use their corresponding camera types (e.g. RtspCameraProvider.CAMERA_ADDED now has type `Event[RtspCamera]`)

use generic camera type `T` for `CAMERA_ADDED` event parameter

---

rosys/geometry/rotation.py
rosys/hardware/gnss.py

This PR adds handy properties to `Rotation` to get roll, pitch and yaw in degrees, like the ones we have in `Pose`.
For context, the old description:
> Our robot's gnss antennas are quite high above the ground and to calculate the correct position on ground level, we have to add the z coordinate to the `antenna_pose`.
> I also added handy degree properties to `Rotation`, like the ones we have in `Pose`.

Add properties to Rotation to get roll, pitch and yaw in degrees

---

rosys/hardware/gnss.py

While setting up a test for a new gnss antenna configuration, I noticed that the location noise of the gnss simulation is wrong.
When using `_lat_std_dev=1` and `_lon_std_dev=0`, I got this result which makes sense, because we have two cases:
1. noise_lat is positive, which leads to both a positive direction and distance for polar, resulting in a spread on positive x
2. noise_lat is negative, which leads to both negative values canceling each other out, also resulting in a positive spread
After the fix, I recorded both `_lat_std_dev` and `_lon_std_dev` alternating between 0 and 1, which led to an expected cross:
Setting both to 1 also shows the expected pattern:

Fix Gnss noise calculation in simulation

---

rosys/run.py
tests/test_run.py

We encounter the situation quite often where we want to run a hardware controlling function that can fail because of timings for example. But running it in a loop until it's done is problematic aswell.
So this PR adds the `retry` function wrapper, that runs a given function with a maximum number of tries and and other optional parameters like a timeout and a `on_failed` function that is called when an attempt fails.
@falkoschindler I'm not sure whether we should return a boolean or the return value of the function or both. Probably both?

Add retry utility for handling function retries

---

rosys/hardware/bumper.py
rosys/hardware/estop.py

The bumper and estops still use the `level` of the Inputs. With the introduction of the `active` property to Lizard in https://github.com/zauberzeug/lizard/pull/38 we can make the code more readable and understandable. This also allows us to invert the inputs for specific robot configurations.
With this change we will need to reconfigure our robots to use `active` instead of `level`. This is a breaking change.

Estop and bumper use active

---

rosys/rosys.py

The `rosys.notify` function always logged as info from rosys.rosys and did not relay NiceGUI keyword arguments so that i.e. the position could not be changed.
Before:
```
2025-04-28 10:49:53.654 [INFO] rosys/rosys.py:77: Test Message
```
After this change:
```
2025-04-28 10:51:02.194 [your loglevel] your_project/your_file.py:line: Test Message
```

Add configurable logging level and nicegui keyword arguments to notify function

---

rosys/hardware/gnss.py

This PR makes various fixes to ensure we do not run into time discrepancies between NMEA messages and RoSys:
- clearing the serial buffer before starting the processing loop ensures we start fresh and do not spend time processing old messages
-  increasing the baud rate ensures we are reading as fast as possible
- warn when timestamps between RoSys and NMEA diverge more than 50 ms (which is kind of a barrier for a functioning Kalman Filter when driving about 1 km/h)
- debug log the time diff for easier debugging

Improve GNSS message processing to avoid time discrepancies between NMEA messages and RoSys

---

rosys/hardware/gnss.py

When no GNSS signal is available, the NMEA messages are empty (`$GPGGA,,,,,,,,,`) and the current code fails when it tries to extract a timestamp.

Handle missing NMEA timestamp

---

rosys/persistence/backup_schedule.py
rosys/rosys.py

We had issues running our tests with multiple fixtures, because the persistence keys were not cleared after a test.
```
if key is None:
key = self.__module__
if not key.strip('.'):
raise ValueError('Key is empty')
if not KEY_PATTERN.match(key):
raise ValueError(f'Key "{key}" contains invalid characters')
if key in self.instances:
>           raise ValueError(f'Key "{key}" is already used by another persistent object')
E           ValueError: Key "field_friend.robot_locator" is already used by another persistent object
../rosys/rosys/persistence/persistable.py:57: ValueError
```

Clear `Persistable` instances after test

---

fetch_milestone.py

We introduced a new "breaking change" label, but had to make sure to remember it when writing release notes ([0.24.0](https://github.com/zauberzeug/rosys/releases/tag/v0.24.0)).
This PR adds the following line below pull requests with this label:
> ⚠️  **Breaking change:** TODO: add information regarding the breaking change
Full output:
```
❯ python3 fetch_milestone.py 0.24.0
- Add gnss timestamp to `GnssMeasurement` (#288 by @Johannes-Thiel)
- Improve GNSS message processing to avoid time discrepancies between NMEA messages and RoSys (#285 by @rodja)
- Implement new esp disabling (#284 by @pascalzauberzeug)
- Add another dahua mac prefix (#283 by @denniswittich)
- add reolink vendor mac and url (#282 by @NiklasNeugebauer)
- Allow inverting e-stops and bumpers (#281 by @Johannes-Thiel)
⚠️ …
```

Generate breaking change warnings for release notes

---

rosys/automation/app_controls_.py
rosys/hardware/__init__.py
rosys/hardware/bms.py
rosys/hardware/robot_brain.py

We had issues where hardware commands were sent before the ESP was done booting and instead of just trying to re-send the commands, this PR does:
1. Add `RobotBrain.is_ready` property based on `RobotBrain.hardware_time`
2. Make use of new `espresso.py` optional for enable and reset, but keep `flash.py` as default for now
3. Raise new `EspNotReadyException`, when trying to send a Lizard command when the ESP is not ready
4. Remove old enable etc. notifications, that were not accurate and quite spamy
5. Implement new features in `AppControls` and `BmsHardware`, because they failed when I tested this PR

Improve ESP ready state handling

---

rosys/driving/driver.py

There was a hardcoded minimum length for splines in the `Driver` class, which was too high for our needs.
I decided against another parameter for `drive_spline`, because I would have to add it to `drive_path` and `drive_to` as well, which is already quite cluttered. Instead I used `DriveParameters` and kept the old distance of 1cm as the default value.

Make the driver's minimum spline length configurable

---

rosys/hardware/robot.py

When working on robots and introducing new properties to be checked with lizard, it is easy to forget to configure the robot. This is also relevant when changing branches on the robot. This PR aims to notify the user that there is something wrong with the configuration.
To detect a faulty configuration we are comparing the number of arguments in the `output_fields` with the length of the provided `core_message`. I chose this way of comparison due to the ease of implementation. This will cover most wrong configurations, the only problem will be if two configurations have the same number of paramters, but these parameters are diffrent. This is not a usual case since in practice we mostly add new parameters or remove them. Not change the parameter.
We add `+2` the the `output_length` due to …

Add a notification to warn about wrong Lizard configuartion

---

rosys/hardware/gnss.py

With https://github.com/zauberzeug/rosys/pull/285 we introduced a check if the delay between the GNSS messages and the time when RoSys handles them is too big.
From there we noticed that if some piece of code blocks the main loop for too long, a lot of GNSS updates will be discarded.
The following log is an example for that. The decreasing difference hints that it needs to work of a queue one by one until messages are accepted again.
```
13.876s BLOCKING CODE DONE
13.932s timestamp diff = -0.433s (exceeds threshold of 0.1)
13.939s timestamp diff = -0.439s (exceeds threshold of 0.1)
13.941s timestamp diff = -0.441s (exceeds threshold of 0.1)
13.943s timestamp diff = -0.343s (exceeds threshold of 0.1)
13.945s timestamp diff = -0.345s (exceeds threshold of 0.1)
13.947s timestamp diff = …
```

Reset GNSS buffer after discarding a late message

---

rosys/driving/driver.py

Currently, the stopping behaviour with throttle_at_end in Driver.drive_spline is not configurable.
This leads to robots (such as the Field Friend) taking a long time to come to a stop.
This could be optimized, but the ramp settings are not configurable.
To allow for changing of the throttling behaviour, we simply swap the ramp arguments with values we add to the driver parameters.
Thus, we can set the min speed (as a factor) and the distance to start throttling.
Perhaps, the code needs some more changes if the throttle distance is larger than the hook distance.

Make throttle at end ramp configurable

---

rosys/hardware/robot_brain.py

When restarting the ESP via `robot_brain.restart()`, it is possible to cause a `TimeoutError` if the ESP is not sending core messages. This exception should be caught and ignored because it is not relevant for the restart procedure.
I simply added an `except` block.
I also changed a related comment to use the `NOTE` marker instead of `Note` to improve discoverability and support VSCode's built-in to-do list features.

Ignore `TimeoutError` when restarting the ESP

---

.github/workflows/publish.yml
.github/workflows/pytest.yml
.pre-commit-config.yaml
Dockerfile
docker-compose.yml
poetry.lock
pyproject.toml
rosys.code-workspace
rosys/analysis/kpi_buckets.py
rosys/analysis/kpi_logger.py
rosys/event.py
rosys/geometry/object3d.py
rosys/geometry/pose3d.py
rosys/hardware/gnss.py
rosys/pathplanning/area.py
rosys/persistence/persistable.py
rosys/run.py
rosys/testing/log_configuration.py
rosys/vision/camera/calibratable_camera.py
rosys/vision/camera/camera.py
rosys/vision/image.py
rosys/vision/image_rotation.py
rosys/vision/mjpeg_camera/motec_settings_interface.py
rosys/vision/rtsp_camera/rtsp_camera.py
rosys/vision/rtsp_camera/rtsp_device.py

Until now RoSys didn't officially support for Python 3.13.
So we added it to the build pipeline and upgraded corresponding settings.

Upgrade to Python 3.13 as the default version, drop support for Python 3.10

---

rosys/hardware/imu.py

For testing purposes in https://github.com/zauberzeug/field_friend/pull/361 I needed to simulate pitch and roll with the IMU. These values can now be set via the developer ui or code, that's why I made all variables public. Before only the noise was configurable. Yaw is still bound to a `PoseProvider`.

Expand IMU simulation by roll and pitch

---

rosys/driving/driver.py

The driver has the parameter `minimum_drive_distance`, which prevents it from driving splines that are too short. Too short splines can lead to weird turning movements, that's why we want to avoid it.
The problem occurs when we use `drive_spline` with `stop_at_end=False` and after that we try to drive a spline that is too short but this time with `stop_at_end=True`. Regardless whether the robot drives the spline or not, we expect it to stop.
Therefore I let the wheels stop if the spline is too short and `stop_at_end` is `True`.
Here is a short example that shows the behaviour:
```python
#!/usr/bin/env python3
import rosys
from rosys.geometry import Pose, Spline
wheels = rosys.hardware.WheelsSimulation()
robot = rosys.hardware.RobotSimulation([wheels])
odometer = …
```

Stop driver when spline is too short and stop_at_end is True

---

rosys/hardware/gnss.py

Before, the developer ui of the GNSS module was fixed to a single column. The default behaviour is still the same, but the base ui and the simulation ui can be displayed side by side by putting `ui.row` around it.
The column around the base ui is necessary to have the headline in the same column as the grid.

Restructure GNSS developer ui to make it more flexible

---

rosys/analysis/kpi_page_.py

I moved the ui code of the KPI page to a `_content` method. This allows customizing the ui of pages that extend `kpi_page`, like adding a header by overwriting `_content`

Allow customization of the KPI page

---

rosys/hardware/estop.py

There was an inconsistency with `EStopHardware` and the software EStop and their event handling. This PR restructures the base class and correctly handles the `ESTOP_TRIGGERED` and `ESTOP_RELEASED` events.

Correctly handle EStop events

---

docs/examples/automations/README.md
docs/examples/automations/main.py
rosys/automation/__init__.py
rosys/automation/automation.py
rosys/automation/parallelize.py
tests/test_automations.py

@pascalzauberzeug wondered if we could implement a decorator for marking parts of an automation as uninterruptible so that they keep running until completed when pausing an automation.
With the help of GPT-5 I came up with such a decorator that seems to work nicely:
```py
async def a():
for i in range(10):
print(f'a - {i}')
await asyncio.sleep(0.1)
@rosys.automation.uninterruptible
async def b():
for i in range(10):
print(f'b - {i}')
await asyncio.sleep(0.1)
async def c():
for i in range(10):
print(f'c - {i}')
await asyncio.sleep(0.1)
async def automation():
await a()
await b()
await c()
automator = rosys.automation.Automator(steerer=None, default_automation=automation)
ui.button('start automation', on_click=automator.start)
ui.button('pause automation', on_click=lambda: …
```

Introduce `@automation.uninterruptible` decorator

---

rosys/analysis/logging_page.py
rosys/analysis/videos_page_.py

As I already did for the KPI page in https://github.com/zauberzeug/rosys/pull/327, I moved the content of the logging and video pages from the page declarator into another function.
This allows giving the pages a custom header for example, like I did in https://github.com/zauberzeug/field_friend/pull/376.

Make logging and video pages customizable

---

rosys/vision/__init__.py
rosys/vision/record_replay/__init__.py
rosys/vision/record_replay/constants.py
rosys/vision/record_replay/image_recorder.py
rosys/vision/record_replay/replay_camera.py
rosys/vision/record_replay/replay_camera_provider.py
rosys/vision/simulated_camera/simulated_device.py
tests/conftest.py
tests/test_recorder_replay.py

We needed a lightweight solution to record image data and play them back for development purpose. 
Adds `ImageRecorder` that saves all incoming images for one camera provider.
Adds `ReplayCameraProvider` that acts as a camera provider but emits the previously recorded images.

Add image recorder / replay module
