zauberzeug/rosys

poetry.lock
pyproject.toml
rosys/actors/lizard.py
rosys/ui/__init__.py
rosys/ui/configure.py
rosys/ui/lizard_stats.py

Adds lizard statistics (responsiveness, update and processing duration)

Lizard stats

---

rosys/vision/usb_camera_provider_hardware.py

Quick overview:
Problem: We were experiencing crashes when `get_images` was executed from within `set_parameters` on Jetson Orin Nano.
Solution: I've added thread synchronization to prevent concurrent execution of these functions, eliminating the crashes.
Testing: I've tested the changes on a Jetson Orin Nano, and it's running smoothly without crashes.

added lock to prevent crash on parameter update

---

rosys/hardware/bumper.py

This PR allows the bumper to be uses with a Lizard Expander.

Add Expander option to Bumper

---

rosys/vision/camera.py

This PR improves the "latest image" properties and provides a new one to retrieve the newest one with detections.

Add property to get latest image which has detections

---

rosys/driving/driver.py

This PR introduces the `backward` bool property for the `drive_to` method.

allow driving backwards

---

rosys/vision/camera/camera.py

This PR adds the type annotation to `Camera.images`.

Add typing to Camera.images

---

rosys/vision/image.py

This PR includes the available types in the exception.

improve error message for multiple detection types

---

rosys/vision/usb_camera/usb_camera.py

This pull request makes the reading of a usb camera image async.

make capture_image async

---

rosys/analysis/kpi_page_.py

Use echarts instead of highcharts on the KPI page since echarts comes with nicegui and doesn't require an additional package to be installed.

use echarts instead of highcharts

---

poetry.lock
pyproject.toml

This pull request allows flashing esp32 firmware on production systems by elevating the dependency.

moved esptool dev dependency to main dependencies

---

examples/kpi/main.py
rosys/analysis/__init__.py
rosys/analysis/kpi_chart.py
rosys/analysis/kpi_page_.py

Rework of the KPI Page:
* instead of `positives` and `negatives` hand the KPI Page a list of `charts` to display
* add `KPIChart` class to define title, incidents/indicators and the color for this chart
* use `matplotlib` colormaps to define colors for a chart
* add KPI Page example

Rework kpi page

---

rosys/driving/keyboard_control_.py

This PR adds a `ui.timer` to `KeyboardControl` that checks the client connection every 0.5 seconds. If a JavaScript command times out after 0.5 seconds, the steerer is stopped.
Open questions:
- Should we enable this safety feature by default?
- Is the 0.5 seconds interval and 0.5 seconds timeout too loose or too tight?

Stop steerer when client connection is interrupted

---

rosys/vision/detections.py
rosys/vision/detector.py
rosys/vision/detector_hardware.py
rosys/vision/detector_simulation.py
rosys/vision/image.py

This pull request lays the groundwork for custom detector upload logic.

Detector upload

---

rosys/hardware/robot.py

add Docstring to RobotHardware
---
Feature request: #85

Add docstring

---

rosys/hardware/robot_brain.py

This PR computes the clock offset between microcontroller and RoSys more robustly. Instead of using a single measurement only, it holds a history of 100 measurements and computes the offset by taking the average. This improves time-sensitive operations significantly.

Compute a more robust clock offset

---

rosys/analysis/__init__.py
rosys/analysis/logging_page.py

This PR introduces a page mounted at /logging to change the log levels of all registered loggers.

Introduce logging page

---

rosys/automation/automator.py

This pull request adds `set_default_automation` to the `automator` which is handy for usage in lambda statements.

Provide setter for default automation

---

rosys/persistence/converters.py

This PR logs some data if conversion `from_dict` fails.

Provide more information about conversion errors

---

rosys/geometry/pose.py

This PR adds a function to pose-transform a Point3d like it was already possible with 2d points.

Add transform3d function to pose to move a 3d point in relation to the given pose.

---

rosys/driving/steerer.py

This PR reverts commit 400501c6ea20806a6dc1a2e0ee4b0d5dc82891f4 because it made driving backwards with fine adjustments to the direction very difficult.

Simplify steering without fancy dead band regions and inversions.

---

rosys/hardware/estop.py

This pull request adds a logging info if an e-stop is triggered.

Log e-stops

---

rosys/vision/simulated_camera/simulated_camera.py

This pull request adds the `TransformableCamera` mixin to the `SimulatedCamera` to provide crop and and rotation properties. This makes the simulation better interchangeable with the `UsbCamera`.

Make SimulatedCamera Transformable

---

rosys/geometry/point3d.py

Add factory function to create a `Point3d` from a `Point`.

Create point3d from point

---

rosys/hardware/lizard_firmware.py
rosys/hardware/robot_brain.py

As described in https://github.com/zauberzeug/rosys/issues/157 flashing p0 currently does not work via ui.
I currently don't have to hardware on hand to test it and it's not the most elegant solution, but I think it's a good starting point.

Fix p0 flashing

---

examples/camera_arm/main.py
rosys/driving/odometer.py

Thanks to #153 we now can use reference frames to calculate coordinates. This PR provides a `prediction_frame` for the `Odometer` to make using coordinates on the robot more convinient.

Provide auto-updated `Odometer.prediction_frame`

---

rosys/vision/detector_simulation.py

This PR activates the the newly introduced frame3d capabilities of the camera calibration (#153) for the `DetectorSimulation`.

Use new frame resolving in `DetectorSimulation`

---

poetry.lock
pyproject.toml
rosys/analysis/tracking.py
rosys/automation/parallelize.py
rosys/vision/camera/camera.py
tests/test_automations.py

- enable `RUF006` and fix the resulting occurrence in camera
- enable `check_untyped_defs = true` to also use functions that are not explicitly typed and fix two occurrences
- update debugpy, since version 1.8.3 was pulled
- fix typing and exception handling in parallelize.py

Some house keeping

---

.github/workflows/pytest.yml

This PR adds the pre-commit hooks to the pipeline checking for ruff errors, whitespaces and double quotes.

add pre-commit to pytest ci

---

rosys/vision/rtsp_camera/jovision_rtsp_interface.py
rosys/vision/rtsp_camera/rtsp_camera.py
rosys/vision/rtsp_camera/rtsp_device.py

Uses httpx instead of requests to send and request parameters to/from Jovision RTSP cameras.

Async Jovision parameter setting

---

rosys/vision/camera/camera.py

reduce default number of images stored in `Camera` to 4

Make image history length configurable

---

rosys/vision/detector_hardware.py

pass optional information about the image source to the detector so it can be uploaded to the learning loop.
This feature requires a detector node using nodelib version 0.10.13 or higher.
Older detectors will still do the inference but will not transport this information to the learning loop.

feature: detector, add source when uploading image

---

rosys/vision/mjpeg_camera/mjpeg_camera.py
rosys/vision/usb_camera/usb_camera.py

I think https://github.com/zauberzeug/rosys/pull/197 missed these two lines.

Remove polling interval assignment

---

rosys/vision/simulated_camera/simulated_device.py

The time displayed in the image didn't match the timestmap of the image.

Fix time in simulated camera images

---

rosys/vision/rtsp_camera/rtsp_camera_provider.py
rosys/vision/rtsp_camera/vendors.py

adds a missing mac group for dahua rtsp cameras.

add dahua mac group

---

rosys/vision/calibration.py

feat: set balance to more sensible 0.5
refactor: reuse function

small calibration changes

---

rosys/helpers/lazy_worker.py
rosys/vision/detections.py
rosys/vision/detector.py
rosys/vision/detector_hardware.py
rosys/vision/detector_simulation.py

Improve detector API. 
This PR adds methods that wrap detector functionalities.

Detector hardware features

---

rosys/hardware/estop.py

Add a event to the estop class that triggers, when the Estop is released.

add estop release event

---

rosys/vision/detector_hardware.py

-  move `image.set_detections` and `NEW_DETECTIONS.emit` from `_detect` into `detect`.
This allows `_detect` to be overwritten more easily

Later Detection Emit

---

rosys/helpers/deprecation.py

- add proper wrapper to function decarator
- replace `__init__` in class decorator

Only show deprecation warnings on call

---

rosys/vision/detections.py
rosys/vision/detector_hardware.py

Adds model for classification detections -- a possible return value of a detector.

Add classification detections

---

rosys/vision/image.py
tests/test_image.py

Adds methods to convert between rosys image and PIL image

Rosys PIL image conversion

---

rosys/vision/detections.py

Before, the color was hardcoded and I just changed it to a keyword argument. I kept shrink as a positional argument to keep compatibility.

Make color parameter configurable in detection SVG rendering

---

rosys/vision/rtsp_camera/vendors.py

This adds a vendor mac and corresponding rtsp url generation for reolink ip cameras

add reolink vendor mac and url

---

rosys/vision/rtsp_camera/vendors.py

Adds the vendor type "Uniarch"

Add Vendor: Uniarch

---

rosys/vision/calibration.py

Hardcoded tolerance of 2 px was too small for large images
Instead use a configurable fraction of the max image size
Done

Custom reprojection tolerance

---

rosys/vision/__init__.py
rosys/vision/annotations.py
rosys/vision/detector_hardware.py

Implements API calls for new Learning Loop Node (> 0.17.0).
Besides some simplifications, the new API allows to upload annotations.
Add data classes for annotations.
Modify API calls

Learning Loop Node 0.17
